# Generated by Django 5.2.4 on 2025-07-08 16:08

import StarInTheKitchen.app_users.validators
import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2, message='First name needs to be at least 2 characters long.'), StarInTheKitchen.app_users.validators.first_name_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Last name needs to be at least 2 characters long.'), StarInTheKitchen.app_users.validators.last_name_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile_picture_s6ec3k', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
